// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA808uYfqIlnzpCNAy5lNpg0sde8tDqBq8',
    appId: '1:421355477489:android:1abc351d3292f4047f0c50',
    messagingSenderId: '421355477489',
    projectId: 'trustay-ac768',
    storageBucket: 'trustay-ac768.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnnGvRwJu_K4KCu0s5z1HArIWbK338xn8',
    appId: '1:421355477489:ios:f9ef5988ca8411367f0c50',
    messagingSenderId: '421355477489',
    projectId: 'trustay-ac768',
    storageBucket: 'trustay-ac768.firebasestorage.app',
    androidClientId: '421355477489-3h7b8u1qlvgaj6bg80ld49i6s05k1g8u.apps.googleusercontent.com',
    iosClientId: '421355477489-cvqsvpakmiob5kpg89690s9eo9s6lcpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.front',
  );
}
